services:
  dev-postgres:
    image: postgres:latest
    container_name: dev-postgres
    hostname: dev-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      PGTZ: Asia/Tokyo
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - dev-postgres-volume:/var/lib/postgresql/data

volumes:
  dev-postgres-volume:
    name: dev-postgres-volume
    driver: local

